/*
Copyright © 2025 Joseph Goksu josephgoksu@gmail.com
*/
package cmd

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"
	"time"

	handlers "github.com/josephgoksu/TaskWing/internal/handlers"
	"github.com/josephgoksu/TaskWing/internal/render"
	"github.com/josephgoksu/TaskWing/internal/task"
	"github.com/josephgoksu/TaskWing/internal/ui"
	"github.com/josephgoksu/TaskWing/internal/utils"
	"github.com/spf13/cobra"
)

// planCmd is the parent for plan management subcommands.
//
// Human-facing subcommands mirror `taskwing task`:
//
//	plan list           list all plans
//	plan show <id>      show one plan in detail
//	plan current        show the active plan
//	plan set-active <id> switch the active plan
//	plan delete <id>    delete a plan and its tasks
//
// The JSON-blob entry point used by the /taskwing:plan slash command lives at
// `plan tool --params <json>` so it's still callable from skills.
var planCmd = &cobra.Command{
	Use:   "plan",
	Short: "Manage plans (list, show, current, set-active, delete, tool)",
	Long: `Manage TaskWing plans.

Plans group related tasks generated by the clarify-decompose-expand flow.
The list/show/current subcommands give a human-friendly view; the tool
subcommand exposes the JSON-blob entry point used by the /taskwing:plan
slash command in your AI tool.`,
}

func init() {
	rootCmd.AddCommand(planCmd)
	planCmd.AddCommand(planListCmd)
	planCmd.AddCommand(planShowCmd)
	planCmd.AddCommand(planCurrentCmd)
	planCmd.AddCommand(planSetActiveCmd)
	planCmd.AddCommand(planDeleteCmd)
	planCmd.AddCommand(planToolCmd)

	planToolCmd.Flags().StringVar(&planParamsRaw, "params", "", "JSON params blob; use '-' to read from stdin")
	_ = planToolCmd.MarkFlagRequired("params")

	planDeleteCmd.Flags().Bool("force", false, "Skip confirmation prompt")
}

// ── plan list ────────────────────────────────────────────────────────────────

var planListCmd = &cobra.Command{
	Use:   "list",
	Short: "List all plans",
	Long: `List every plan with id, status, task count, and goal.

Examples:
  taskwing plan list`,
	RunE: runPlanList,
}

func runPlanList(cmd *cobra.Command, args []string) error {
	repo, err := openRepoOrHandleMissingMemory()
	if err != nil || repo == nil {
		return err
	}
	defer func() { _ = repo.Close() }()

	plans, err := repo.ListPlans()
	if err != nil {
		return fmt.Errorf("list plans: %w", err)
	}

	if isJSON() {
		return printJSON(plans)
	}

	if len(plans) == 0 {
		fmt.Println("no plans found. use /taskwing:plan in your AI tool to create one.")
		return nil
	}

	active, _ := repo.GetActivePlan()
	activeID := ""
	if active != nil {
		activeID = active.ID
	}

	if ui.IsInteractive() {
		ui.SectionHeader("Plans")
	}

	tbl := render.NewTable(os.Stdout, []string{"ID", "STATUS", "TASKS", "CREATED", "GOAL"}).
		Width(100).
		RightAlign(2)
	for _, p := range plans {
		idCell := utils.ShortID(p.ID, utils.TaskIDLength)
		if p.ID == activeID {
			idCell = "* " + idCell
		}
		tbl.Row(
			idCell,
			string(p.Status),
			fmt.Sprintf("%d", p.GetTaskCount()),
			p.CreatedAt.Format("2006-01-02"),
			p.Goal,
		)
	}
	tbl.Render()

	fmt.Println()
	fmt.Printf("total    %d plan(s)\n", len(plans))
	if activeID != "" {
		fmt.Printf("active   %s  (marked with *)\n", utils.ShortID(activeID, utils.TaskIDLength))
	}
	return nil
}

// ── plan show ────────────────────────────────────────────────────────────────

var planShowCmd = &cobra.Command{
	Use:   "show [plan-id]",
	Short: "Show one plan in detail",
	Args:  cobra.ExactArgs(1),
	RunE:  runPlanShow,
}

func runPlanShow(cmd *cobra.Command, args []string) error {
	repo, err := openRepoOrHandleMissingMemory()
	if err != nil || repo == nil {
		return err
	}
	defer func() { _ = repo.Close() }()

	planID, err := resolvePlanID(repo, args[0])
	if err != nil {
		return err
	}

	p, err := repo.GetPlanWithPhases(planID)
	if err != nil {
		return fmt.Errorf("get plan: %w", err)
	}

	if isJSON() {
		return printJSON(p)
	}

	renderPlanRecord(p)
	return nil
}

// ── plan current ─────────────────────────────────────────────────────────────

var planCurrentCmd = &cobra.Command{
	Use:   "current",
	Short: "Show the active plan",
	RunE:  runPlanCurrent,
}

func runPlanCurrent(cmd *cobra.Command, args []string) error {
	repo, err := openRepoOrHandleMissingMemory()
	if err != nil || repo == nil {
		return err
	}
	defer func() { _ = repo.Close() }()

	p, err := repo.GetActivePlan()
	if err != nil {
		return fmt.Errorf("get active plan: %w", err)
	}
	if p == nil {
		if isJSON() {
			return printJSON(nil)
		}
		fmt.Println("no active plan. use `taskwing plan set-active <id>` or /taskwing:plan to create one.")
		return nil
	}

	if isJSON() {
		return printJSON(p)
	}

	renderPlanRecord(p)
	return nil
}

// ── plan set-active ──────────────────────────────────────────────────────────

var planSetActiveCmd = &cobra.Command{
	Use:   "set-active [plan-id]",
	Short: "Switch the active plan",
	Args:  cobra.ExactArgs(1),
	RunE:  runPlanSetActive,
}

func runPlanSetActive(cmd *cobra.Command, args []string) error {
	repo, err := openRepoOrHandleMissingMemory()
	if err != nil || repo == nil {
		return err
	}
	defer func() { _ = repo.Close() }()

	planID, err := resolvePlanID(repo, args[0])
	if err != nil {
		return err
	}

	if err := repo.SetActivePlan(planID); err != nil {
		return fmt.Errorf("set active plan: %w", err)
	}

	if isJSON() {
		return printJSON(map[string]any{"id": planID, "active": true})
	}
	fmt.Printf("status   active\n")
	fmt.Printf("id       %s\n", planID)
	return nil
}

// ── plan delete ──────────────────────────────────────────────────────────────

var planDeleteCmd = &cobra.Command{
	Use:   "delete [plan-id]",
	Short: "Delete a plan and its tasks",
	Args:  cobra.ExactArgs(1),
	RunE:  runPlanDelete,
}

func runPlanDelete(cmd *cobra.Command, args []string) error {
	repo, err := openRepoOrHandleMissingMemory()
	if err != nil || repo == nil {
		return err
	}
	defer func() { _ = repo.Close() }()

	planID, err := resolvePlanID(repo, args[0])
	if err != nil {
		return err
	}

	force, _ := cmd.Flags().GetBool("force")
	if !force && !isJSON() {
		p, err := repo.GetPlan(planID)
		if err != nil {
			return err
		}
		fmt.Printf("\n  plan   %s\n", p.ID)
		fmt.Printf("  goal   %s\n", p.Goal)
		fmt.Printf("  tasks  %d\n\n", p.GetTaskCount())
		if !confirmOrAbort("delete this plan and all its tasks? [y/N]: ") {
			return nil
		}
	}

	if err := repo.DeletePlan(planID); err != nil {
		return fmt.Errorf("delete plan: %w", err)
	}

	if isJSON() {
		return printJSON(map[string]any{"id": planID, "deleted": true})
	}
	fmt.Printf("status   deleted\n")
	fmt.Printf("id       %s\n", planID)
	return nil
}

// ── plan tool (JSON-blob entry, used by the /taskwing:plan slash command) ────

var planParamsRaw string

var planToolCmd = &cobra.Command{
	Use:   "tool",
	Short: "Run a plan action from a JSON params blob (advanced, used by slash commands)",
	Long: `Run a plan action by passing the full params object as JSON.

This is the entry point the /taskwing:plan slash command uses. Humans
typically want one of the higher-level subcommands (list, show, current,
set-active, delete) and the /taskwing:plan flow itself for clarify and
generate. Reach for this only when you need the raw tool contract.

Actions: clarify, decompose, expand, generate, finalize, audit.`,
	Example: `  taskwing plan tool --params '{"action":"clarify","goal":"add stripe billing"}'
  echo '{"action":"decompose","clarify_session_id":"...","enriched_goal":"..."}' \
    | taskwing plan tool --params -`,
	RunE: runPlanTool,
}

func runPlanTool(cmd *cobra.Command, args []string) error {
	raw, err := readParamsBlob(planParamsRaw)
	if err != nil {
		return err
	}

	var params handlers.PlanToolParams
	if err := json.Unmarshal(raw, &params); err != nil {
		return fmt.Errorf("parse --params JSON: %w", err)
	}

	repo, err := openRepoOrHandleMissingMemory()
	if err != nil || repo == nil {
		return err
	}
	defer func() { _ = repo.Close() }()

	ctx, cancel := context.WithTimeout(cmd.Context(), 5*time.Minute)
	defer cancel()

	result, err := handlers.HandlePlanTool(ctx, repo, params)
	if err != nil {
		return err
	}

	return printJSON(result)
}

// ── helpers ──────────────────────────────────────────────────────────────────

// renderPlanRecord prints a Plan as a compact key:value record, mirroring
// the shape of renderTaskRecord. Phases and tasks render as nested lists.
func renderPlanRecord(p *task.Plan) {
	r := render.NewRecord(os.Stdout)
	r.Inline("id", p.ID)
	r.Inline("status", string(p.Status))
	r.Inlinef("tasks", "%d", p.GetTaskCount())
	if !p.CreatedAt.IsZero() {
		r.Inline("created", p.CreatedAt.Format("2006-01-02 15:04"))
	}
	if !p.UpdatedAt.IsZero() && !p.UpdatedAt.Equal(p.CreatedAt) {
		r.Inline("updated", p.UpdatedAt.Format("2006-01-02 15:04"))
	}
	if p.GenerationMode != "" {
		r.Inline("mode", string(p.GenerationMode))
	}
	r.End()

	if p.Goal != "" {
		fmt.Println()
		fmt.Println("goal")
		fmt.Printf("  %s\n", p.Goal)
	}
	if p.EnrichedGoal != "" && p.EnrichedGoal != p.Goal {
		fmt.Println()
		fmt.Println("enriched-goal")
		for _, line := range strings.Split(strings.TrimSpace(p.EnrichedGoal), "\n") {
			fmt.Printf("  %s\n", line)
		}
	}

	if len(p.Phases) > 0 {
		fmt.Println()
		fmt.Printf("phases (%d)\n", len(p.Phases))
		for i, ph := range p.Phases {
			fmt.Printf("  %d. %s\n", i+1, ph.Title)
			if ph.Description != "" {
				fmt.Printf("     %s\n", ph.Description)
			}
		}
	}

	if len(p.Tasks) > 0 {
		fmt.Println()
		fmt.Printf("tasks (%d)\n", len(p.Tasks))
		tbl := render.NewTable(os.Stdout, []string{"  ID", "STATUS", "PRI", "TITLE"}).
			Width(100).
			RightAlign(2)
		for _, t := range p.Tasks {
			tbl.Row(
				"  "+utils.ShortID(t.ID, utils.TaskIDLength),
				string(t.Status),
				fmt.Sprintf("%d", t.Priority),
				t.Title,
			)
		}
		tbl.Render()
	}
}

// resolvePlanID accepts a full plan ID or a unique prefix and returns the
// matching ID. Errors when zero or multiple plans match.
func resolvePlanID(repo planLookup, idOrPrefix string) (string, error) {
	plans, err := repo.ListPlans()
	if err != nil {
		return "", err
	}
	var matches []string
	for _, p := range plans {
		if p.ID == idOrPrefix {
			return p.ID, nil
		}
		if strings.HasPrefix(p.ID, idOrPrefix) {
			matches = append(matches, p.ID)
		}
	}
	switch len(matches) {
	case 0:
		return "", fmt.Errorf("no plan matches %q", idOrPrefix)
	case 1:
		return matches[0], nil
	default:
		return "", fmt.Errorf("plan id %q is ambiguous: %s", idOrPrefix, strings.Join(matches, ", "))
	}
}

// planLookup is the minimal interface we need from the memory repo for plan
// commands. Lets resolvePlanID stay testable without dragging in the full repo.
type planLookup interface {
	ListPlans() ([]task.Plan, error)
}

// readParamsBlob reads a JSON params blob from a flag value. If the value is
// "-" it reads from stdin instead. Returns the raw bytes for json.Unmarshal.
func readParamsBlob(flagValue string) ([]byte, error) {
	if flagValue == "-" {
		data, err := io.ReadAll(os.Stdin)
		if err != nil {
			return nil, fmt.Errorf("read stdin: %w", err)
		}
		return data, nil
	}
	if strings.TrimSpace(flagValue) == "" {
		return nil, fmt.Errorf("--params is required (or pass '-' to read from stdin)")
	}
	return []byte(flagValue), nil
}
